version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: lms-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: lms

  backend:
    build: ./server
    container_name: lms-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/lms
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: lms-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
